### PR TITLE
Add the different Catppuccin themes

### PR DESCRIPTION
**Pull request by kkrypt0nn**
Will need the screenshots for the previews to be added

### CODE REVIEW

**Comment by jonpalmisc** [comment]
The "style" field in the theme file is actually meant to specify the [Qt Style](https://doc.qt.io/qt-6/qstyle.html) to use. You probably want to use "Fusion" as the key for all of them, otherwise things won't look great. (See the "Classic Windows"-like styling in the screenshot below which is caused by this.)

Also, selected items in the command palette are invisible:
image

I am assuming that you'll want to fix these (and not want the screenshots to look like this) so I won't merge this just yet.

**Comment by kkrypt0nn** [comment]
Oh thanks for pointing out the `style` and the command palette issue :)

Do you by any chance know if the command pallette has a custom variable for the background or is it just `selectionColor`? Haven't found on where else it is used https://docs.binary.ninja/dev/themes.html#blending-functions

**Comment by kkrypt0nn** [comment]
I've amended the changes to keep it clean as a single commit. The `selectionColor` should be fine with that color even if used somewhere else, would be nice to have it documented on https://docs.binary.ninja/dev/themes.html#blending-functions as well.

**Comment by jonpalmisc** [comment]
Just merged this (albeit, weirdly, so this PR can't auto-close). Nevertheless, this IS merged now. Thanks for the themes!

**Pull request closed without merging**
